version: "3.9"

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always

    ports:
      - "5678:5678"
    extra_hosts:
      - "host.docker.internal:host-gateway"

    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678

    volumes:
      - ./n8n_data:/home/node/.n8n

volumes:
  n8n_data: